### ISSUE TITLE
Login impossible, getting strange exception backtrace

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#21]
If I (Nakaner) go to http://thefive.sabic.uberspace.de/osmbc.html and log me in (via OSM), I only get this exception backtrace:

    Access Forbidden
    
    Error: Access Forbidden
    at /home/thefive/development/osmbc/app.js:123:17
    at findEndFunction (/home/thefive/development/osmbc/model/pgMap.js:217:7)
    at emit (events.js:95:17)
    at Query.handleReadyForQuery (/home/thefive/development/osmbc/node_modules/pg/lib/query.js:91:8)
    at null.<anonymous> (/home/thefive/development/osmbc/node_modules/pg/lib/client.js:163:19)
    at emit (events.js:117:20)
    at Socket.<anonymous> (/home/thefive/development/osmbc/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

    [Go Back to Start](/osmbc.html)

Am I not allowed to use the service or is it a bug?

**Comment by TheFive** [comment]
It is a typo. I have put nakaner as user, but Nakaner is correct. can you try again ?

(The Backtrace is because system is running in "Development Mode"). The important information is "Access Forbidden", what was right in this case :-(. 
I was confused by the session store as you have remarked it the first time.

**Comment by TheFive** [comment]
Error message extended with OSM User Name, so that in case of an error, typos can be easier found.
"OSM User >The_Five< has no access rights."
