### ISSUE TITLE
Give a cookie hint on message: failed to find request token in session

### ISSUE THREAD

**Issue by severak** [TheFive/osmbc#524]
cannot authenticate to OSMBC. Here is the traceback from DEV instance:

```
Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/home/thefive/development/osmbc/node_modules/passport-openstreetmap/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
    at attempt (/home/thefive/development/osmbc/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/thefive/development/osmbc/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/thefive/development/osmbc/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/thefive/development/osmbc/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/thefive/development/osmbc/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/thefive/development/osmbc/node_modules/express/lib/router/layer.js:95:5)
    at /home/thefive/development/osmbc/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:330:12)
    at next (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/home/thefive/development/osmbc/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/home/thefive/development/osmbc/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:312:13)
    at /home/thefive/development/osmbc/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:330:12)
    at next (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/thefive/development/osmbc/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/thefive/development/osmbc/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:312:13)
    at /home/thefive/development/osmbc/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:330:12)
    at next (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/thefive/development/osmbc/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/home/thefive/development/osmbc/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:312:13)
    at /home/thefive/development/osmbc/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:330:12)
    at next (/home/thefive/development/osmbc/node_modules/express/lib/router/index.js:271:10)
Go Back to Start
```

Note that I had "Severák" username in past, now I am "Severak".

**Comment by TheFive** [comment]
Try to delete your local cookies please. That helps with most login issues.

**Comment by fredao** [comment]
den kenne ich gar nicht

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

Am 24.09.2016 7:34 vorm. schrieb "TheFive" <notifications@github.com>:

**Comment by TheFive** [comment]
Hi Severak,
we can not find a Severak User in Def or in Production of OSMBC: Whats your OSM User Name ?

**Comment by TheFive** [comment]
I think i should place my most usefull help regarding this error in the error message display.
So the bug becomes an enhancement:

Give the hint to delete your cookies in the error message display page.

**Comment by TheFive** [comment]
Additional hint: Do not use the old url thefive.sabic.uberspace.de. use thefive.info.

**Comment by severak** [comment]
I am not member of WeeklyOSM. I was just impressed by OSMBC description and wanted to try it.

My OSM account is here - https://www.openstreetmap.org/user/Severak . Previously, my name was "Severák".

**Comment by severak** [comment]
Also https://thefive.info/osmww/auth/done URL seems to have invalid response sometimes...

**Comment by TheFive** [comment]
Mm, there is no public demo yet, I am working on it, i hope the tool can help more communities, for that i need a more fexible sandboy
