### ISSUE TITLE
Error with download.js

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#57]
```console
$ NODE_ENV=development node download.js
Reading Config from: /home/alexandre/Git/osmbc/config.development.json
Import WN WN268
Import WN WN269
Import WN WN270
Import WN WN271
events.js:85
      throw er; // Unhandled 'error' event
            ^
error: relação "blog" não existe
    at Connection.parseE (/home/alexandre/Git/osmbc/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/alexandre/Git/osmbc/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/alexandre/Git/osmbc/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
@TheFive, is it a bug, isn't? `createdb.js` is OK.

**Comment by alexandre-mbm** [comment]
`npm test` / Coverage:
```
 80 passing (39s)
  1 failing

  1) model/blog createNewBlog should createNewArticle with existing WN:

      Uncaught AssertionError: expected '2000-01-02' to equal '2000-01-01'
      + expected - actual

      -2000-01-02
      +2000-01-01
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/model.blog.test.js:78:71
      at null.<anonymous> (test/testutil.js:37:7)
      at Query.handleReadyForQuery (node_modules/pg/lib/query.js:91:8)
      at null.<anonymous> (node_modules/pg/lib/client.js:163:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

**Comment by TheFive** [comment]
mm, if i look at line 78 in the test file, the expected value is 2000-01-02 toLocaleString, which should not be 2000-01-01. The result from the medel layer seems correct, it is the end date of a blog week + 1 day.

**Comment by TheFive** [comment]
I think it makes sense to open one item for each error.

**Comment by alexandre-mbm** [comment]
Is this a timezone issue?

> I think it makes sense to open one item for each error.

I thought as being the same mistake. I do not know.

**Comment by alexandre-mbm** [comment]
I suggest you mark issues of bug with a red label "bug".

**Comment by TheFive** [comment]
download.js imports some data of the german blog, you can skip the step, and create your own test data.

Download.js tries to open the blog at line 146 and 156. It assumes that one of this reads is successfull, and creates a blog variable in this case. There is no error Handling in the case of no connectivity or other problems opening the urls yet.

**Comment by alexandre-mbm** [comment]
> There is no error Handling in the case of no connectivity or other problems opening the urls yet.

I consider this as bug.

**Comment by alexandre-mbm** [comment]
About timezone:
- http://stackoverflow.com/a/9849524
```js
process.env.TZ = 'Europe/Amsterdam' 
d = new Date()
d.toLocaleTimeString()
```
- http://stackoverflow.com/a/10825774
```js
var time = require('time');
var now = new time.Date();
now.setTimezone("America/Los_Angeles");
now.setTimezone("America/New_York");
```

**Comment by alexandre-mbm** [comment]
Sorry, nothing to see.

> There is no error Handling in the case of no connectivity or other problems opening the urls yet.

Okay. I understand now. My configurations are incomplete.

**Comment by TheFive** [comment]
I am just wondering, where the message comes from. It sounds like, that the variable blog is not defined.
I have introduced some debug messages.

But the message can be thrown by the pg module, then states, that the blog table in pg does not exist. Can you check, wether the createdb js has created the tables blog & article in the development database.

**Comment by alexandre-mbm** [comment]
```console
$ NODE_ENV=development node createdb.js
Reading Config from: /home/alexandre/Git/osmbc/config.development.json
Creating Database

/home/alexandre/Git/osmbc/node_modules/should/lib/assertion.js:160
    throw new AssertionError(params);
          ^
AssertionError: expected 'development' to be 'test'
    at Assertion.fail (/home/alexandre/Git/osmbc/node_modules/should/lib/assertion.js:180:17)
    at Assertion.prop.value (/home/alexandre/Git/osmbc/node_modules/should/lib/assertion.js:65:17)
    at Object.clearDB (/home/alexandre/Git/osmbc/test/testutil.js:50:22)
    at Object.<anonymous> (/home/alexandre/Git/osmbc/import/createdb.js:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by alexandre-mbm** [comment]
OK. I did change _ad hoc_ and I worked.

**Comment by TheFive** [comment]
For the CreateDB part see #66.
For the time issue see #67

**Comment by TheFive** [comment]
I have created a new issue for the createdb fix and improvment.

Thanks for the hint with the timezone issue, it looks like it will work, so all topics of this issue, should be solved (or can be traced via another issue).
