### ISSUE TITLE
How to configure an admin user (the first user)?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#63]
## OSM User >Alexandre Magno< has no access rights
```
Error: OSM User >Alexandre Magno< has no access rights
    at /home/alexandre/Git/osmbc/app.js:125:17
    at findEndFunction (/home/alexandre/Git/osmbc/model/pgMap.js:230:7)
    at emit (events.js:107:17)
    at Query.handleReadyForQuery (/home/alexandre/Git/osmbc/node_modules/pg/lib/query.js:91:8)
    at null.<anonymous> (/home/alexandre/Git/osmbc/node_modules/pg/lib/client.js:163:19)
    at emit (events.js:129:20)
    at Socket.<anonymous> (/home/alexandre/Git/osmbc/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```
[Go Back to Start](http://w7650.noip.me:3000/osmbc.html)

**Comment by TheFive** [comment]
You have to create the first OSM User, that is allowed to ise the system by hand.

**Comment by alexandre-mbm** [comment]
You is on vacation and I am not with hurry. I will study more. Because I do not see
reason to create a new user if I have total control of the deploy.
